name: CI
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          
      # 使用 Chrome Action
      - uses: browser-actions/setup-chrome@latest

      - name: Intall deps
        run: npm install
        # run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

      - name: Build
        run: npm run build:prod
